export const fromCkan = {
  help: 'http://localhost:5005/api/3/action/help_show?name=package_show',
  success: true,
  result: {
    assurance: '',
    author: null,
    author_email: null,
    care_setting: [
      'Community health',
      'Dentistry',
      'Hospital',
      'Maternity',
      'Mental health',
      'Pharmacy',
      'GP / Primary care',
      'Social care',
      'Urgent and Emergency Care',
    ],
    contact_details: 'support@prsb.org',
    creator_user_id: '888e4da0-f614-436c-a0eb-fc83fc16033c',
    dependencies: 'Shared Care Record or other infrastructure.',
    description:
      'Part of a suite of social care standards, About Me information is the most important details that a person wants to share with professionals in health and social care.',
    documentation_help_text: '',
    documentation_link: 'https://theprsb.org/current-standards/aboutme/',
    endorsements: '',
    id: '392dabed-9b86-4608-80df-4cb2cd6b7d79',
    isopen: false,
    license_id: null,
    license_title: null,
    maintainer: null,
    maintainer_email: null,
    mandated: '\\true',
    metadata_created: '2021-12-17T15:40:03.882353',
    metadata_modified: '2022-04-07T11:35:08.532645',
    name: 'about-me',
    notes: null,
    num_resources: 0,
    num_tags: 0,
    organization: {
      id: '9d919972-3272-441f-9c6d-ed2745acb2d5',
      name: 'professional-record-standards-body',
      title: 'Professional Record Standards Body',
      type: 'organization',
      description: '',
      image_url: '',
      created: '2021-12-21T15:38:56.264481',
      is_organization: true,
      approval_status: 'approved',
      state: 'active',
    },
    owner_org: '9d919972-3272-441f-9c6d-ed2745acb2d5',
    private: false,
    reference_code: '',
    related_standards:
      'Core Information Standard (CIS) or other standards that use it. E.g. the Digital Care and Support Plan and Urgent Referral from Care Home to Hospital\r\n' +
      'Standard.',
    standard_category: 'Record standard',
    state: 'active',
    status: 'active',
    title: 'About Me',
    topic: [],
    type: 'dataset',
    url: null,
    version: null,
    resources: [],
    tags: [],
    groups: [],
    relationships_as_subject: [],
    relationships_as_object: [],
  },
};
