###################
### Extensions ####
###################
FROM ghcr.io/keitaroinc/ckan:2.9.4

# Switch to the root user
USER root

# Install any system packages necessary to build extensions
# Make sure we install python 3.8, cause CKAN is not compatible with 3.9
RUN apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/v3.13/main \
    python3-dev=3.8.10-r0

# Fetch and build the custom CKAN extensions
RUN pip install -e "git+https://github.com/Marvell-Consulting/ckanext-scheming.git#egg=ckanext-scheming"
RUN pip install -e "git+https://github.com/Marvell-Consulting/ckanext-pages.git#egg=ckanext-pages"

# Add the custom extensions to the plugins list
ENV CKAN__PLUGINS envvars image_view text_view recline_view datastore datapusher scheming_datasets scheming_organizations pages

# Configure ckan
RUN ckan config-tool ${APP_DIR}/production.ini "ckan.plugins = ${CKAN__PLUGINS}"
RUN ckan config-tool ${APP_DIR}/production.ini "scheming.dataset_schemas = ckanext.scheming:ckan_dataset.yaml"
RUN ckan config-tool ${APP_DIR}/production.ini "scheming.organization_schemas = ckanext.scheming:org_with_email.json"
RUN ckan config-tool ${APP_DIR}/production.ini "ckanext.pages.allow_html = True"

RUN cd /srv/app/src/ckanext-scheming && python setup.py install
RUN cd /srv/app/src/ckanext-pages && python setup.py install

# https://github.com/ckan/ckanext-pages#database-initialization
# RUN CKAN_SOLR_URL=http://solr-headless:8983/solr ckan -c ${APP_DIR}/production.ini pages initdb

RUN chown -R ckan:ckan /srv/app

# Setup cron jobs
# Create the log file to be able to run tail
RUN touch /var/log/cron.log
# run at midnight every night
RUN crontab -l | { ckan ; echo "0 0 * * * ckan --config=${APP_DIR}/production.ini search-index rebuild entry" >> /var/log/cron.log } | crontab -

# Run the command on container startup
CMD cron && tail -f /var/log/cron.log

# Switch to the ckan user
USER ckan
